[package]
name = "capa"
version = "0.3.2"
description = "File capability extractor."
authors = ["Marirs <marirs@gmail.com>", "Andrey Mnatsakanov <andrey@3ig.kiev.ua>"]
keywords = ["capa", "fce", "capability", "file"]
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/marirs/capa-rs"
homepage = "https://github.com/marirs/capa-rs"
exclude = ["examples", "data"]
edition = "2021"

[dependencies]
hex = "0.4.3"
itertools = "0.10.3"
pdb = "0.7.0"
petgraph = "0.6.0"
rayon = "1.5.3"
regex = "1.5"
serde = { version = "1", features = ["derive"] }
smda = "0.2.4"
thiserror = "1"
walkdir = "2.3.2"
yaml-rust = "0.4.5"
goblin = { version = "0.5.1", features = ["alloc"] }
maplit = "1"
dnfile = { git = "https://github.com/marirs/dnfile-rs.git", branch = "master" }


[dev-dependencies]
clap = { version = "3.1.18", features = ["cargo", "derive"] }
serde_json = "1"
prettytable-rs = "0.8.0"

[lib]
name = "capa"
path = "src/lib.rs"

[features]
default = ["properties"]
verbose = []
properties = []

[[example]]
name = "capa_cli"
path = "examples/capa_cli.rs"
required-features = ["properties"]

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
debug-assertions = false
debug = false
opt-level = 3
lto = true
